# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72bb3918a48b5c508334a1abf0c08275d1ba710d540130c2daff888cf09862611fbe3d24838d3316cf435231a5514f87313f154ab7a9a31dcb51f0f0de134b84

test:
  secret_key_base: a088f56ea89f6b2e80cd0d2bf041309b1196520b336e9d284fa3b1e74bd6ab8bc928406a3ba80e079958c46d55d6ddb14964e4a3197544cd3b2ea2d9d15657ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
